Safe-DS/API-Editor

- .github/workflows/main.yml
- .github/workflows/pr.yml
- .gitignore
- api-editor/build.gradle.kts
* Bump Kover from 0.4.4 to 0.5.0
* Upload coverage report for PRs only
> build: bump Kover to 0.5.0

- api-editor/client/package-lock.json
- api-editor/client/package.json
Bump react-syntax-highlighter to 15.5.0.
> build: bump react-syntax-highlighter to 15.5.0

- .github/workflows/issue.yml
Automatically add all issues that are created in this repository to the AST22 project.
> ci: add all issues to AST22 project

- api-editor/build.gradle.kts
- api-editor/server/build.gradle.kts
* Update Gradle plugins
* Update Gradle dependencies
Exception: `ktor` (requires more elaborate changes)
> build: bump Gradle plugins and dependencies

- api-editor/server/build.gradle.kts
- api-editor/server/src/main/kotlin/com/larsreimann/api_editor/server/Application.kt
- api-editor/server/src/main/kotlin/com/larsreimann/api_editor/server/Routing.kt
- api-editor/server/src/test/kotlin/com/larsreimann/api_editor/server/ApplicationTest.kt
> build: bump ktor to 2.0.1

- api-editor/client/src/features/annotations/AnnotationImportDialog.tsx
- api-editor/client/src/features/annotations/annotationSlice.ts
- api-editor/data/annotations/minimal_test_package_annotations.json
- api-editor/data/api/minimal_test_package.json
* Make parameters in `api-editor\data\api\minimal_test_package.json` public so they can be annotated.
* Add annotation file for the test package.
* Fix bug that caused import dialog for annotations to stay open after submitting (not worth a separate PR)
In the API Editor frontend:
1. Import API data: `api-editor\data\api\minimal_test_package.json`
2. Import Annotations: `api-editor\data\annotations\minimal_test_package_annotations.json`
Ensure the imports work properly.
> feat: data for minimal test package

- api-editor/gui/src/common/MenuBar.tsx
* Merge "Import" and "Export" menu items into a "File" menu item
* Merge settings into a "Settings" menu item
* Remove breadcrumbs and logo to free up space
1. Run the GUI with
```sh
cd api-editor/gui
npm run dev
```
1. Click all menu items in the menu bar and check that they still work.
> feat: menu bar improvements

- api-editor/gui/package-lock.json
- api-editor/gui/package.json
* Bump @types/jest to 28.1.1
* Bump jest to 28.1.0
* Bump ts-jest to 28.0.4
* Bump typescript to 4.7.3
* Bump vite to 2.9.9
> build: bump GUI build tools

- README.md
Add short project description to README.
> docs: short project description

- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.test.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
- api-editor/gui/src/features/ui/uiSlice.ts
- api-editor/gui/src/features/usages/UsageImportDialog.tsx
Closes #620.
Each keystroke in the filter box that does not change the set of valid filter tokens now "only" causes a delay of 60ms (down from 180ms).
> perf(gui): faster filtering

- .github/workflows/pr.yml
- .gitignore
- api-editor/gui/package.json
Closes #582.
Add another job that computes and uploads the coverage for the GUI tests.
> ci: upload GUI test coverage

- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/model/PythonDeclaration.ts
- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
Closes #618.
Show how many elements are matched by the filter.
> feat(gui): show number of matched elements

- docs/Development/README.md
- docs/Development/how-to-prepare-a-release.md
Describe where to bump version numbers of this project and subsequently create a new release.
> docs: describe how to create a release

- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
- api-editor/gui/src/features/packageData/selectionView/SelectionView.tsx
Closes #654.
Also show action bar when nothing is selected but disable certain action buttons that require a selection.
> feat(gui): always show action bar when tree view is visible

- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #658.
Remove "Expand matched" button from the action bar.
> feat(gui): remove "Expand matched" button

- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/features/packageData/PackageDataImportDialog.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #661.
Only reset the part of the UI state that depends on the current API after a new API is imported.
> feat(gui): only partially reset UI state after API import

- api-editor/gui/package-lock.json
- api-editor/gui/package.json
- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
- api-editor/gui/src/features/packageData/selectionView/SelectionView.tsx
Closes #635.
You can now see the 10 most used values for each parameter, in a bar chart. Grey bars are non literal values, purple ones are literal values.
Click on any parameter and take a look.
> feat: Added value distribution bar chart for parameters in GUI

- api-editor/gui/src/common/DeleteAllAnnotations.tsx
- api-editor/gui/src/common/GenerateAdapters.tsx
- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/annotations/AnnotationImportDialog.tsx
- api-editor/gui/src/features/annotations/CompleteButton.tsx
- api-editor/gui/src/features/annotations/batchforms/DestinationBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/EmptyBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/OldNewBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/TypeValueBatchForm.tsx
- api-editor/gui/src/features/annotations/forms/BoundaryForm.tsx
- api-editor/gui/src/features/annotations/forms/CalledAfterForm.tsx
- api-editor/gui/src/features/annotations/forms/DescriptionForm.tsx
- api-editor/gui/src/features/annotations/forms/EnumForm.tsx
- api-editor/gui/src/features/annotations/forms/GroupForm.tsx
- api-editor/gui/src/features/annotations/forms/MoveForm.tsx
- api-editor/gui/src/features/annotations/forms/RenameForm.tsx
- api-editor/gui/src/features/annotations/forms/TodoForm.tsx
- api-editor/gui/src/features/annotations/forms/TypeValueForm.tsx
- api-editor/gui/src/features/packageData/PackageDataImportDialog.tsx
- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
- api-editor/gui/src/features/usages/UsageImportDialog.tsx
Closes #674.
Use title case for headings and labels of buttons across the application.
> feat(gui): normalize casing of headings and button labels

- .gitignore
- api-editor/gui/src/common/FilterHelpButton.tsx
- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/packageData/model/filters/DoneFilter.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
Closes #664.
New filter `is:done` to show only elements that are marked as complete and have only annotations that are marked as correct.
> feat(gui): filter `is:done`

- api-editor/gui/src/features/filter/SaveFilterDialog.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #716.
* Viewing & changing of filter before saving
* Replace existing filter with same name
> feat(gui): improved saving of filters

- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #750.
* Add a default sorting mode that sorts parameters in the order they are declared and everything else alphabetically
* Also apply sorting and filtering to parameter list in the selection view of functions
> feat(gui): default sorting mode

- api-editor/gui/src/features/menuBar/MenuBar.tsx
- api-editor/gui/src/features/menuBar/SelectionBreadcrumbs.tsx
- api-editor/gui/src/features/packageData/model/PythonDeclaration.ts
Closes #761.
Show breadcrumbs for the selected element in the top-right corner.
> feat(gui): breadcrumbs for selected element

- api-editor/gui/src/features/menuBar/MenuBar.tsx
Closes #740.
Inform the user when clicking "Previous Match" goes back to end of list or "Next match" goes back to its start.
> feat(gui): inform user when previous/next goes back to end/start of list

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGenerator.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/mutable_model/PythonAst.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/transformation/TodoAnnotationProcessor.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGeneratorTest.kt
- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
Closes #731.
`@Todo` annotations can now be added to parameters.
> feat: todo annotation for parameters

- api-editor/gui/src/common/StyledDropzone.tsx
* Show proper affordance on hover (pointer cursor)
* Prevent selection of text
> feat(gui): improve drop zone

- .github/ISSUE_TEMPLATE/missing_annotation.yml
- .github/ISSUE_TEMPLATE/wrong_annotation.yml
* Replaced `@constant`/`@optional`/`@required` with `@value`
* Added an extra field for screenshots
> chore: update issue templates for wrong/missing annotations

- api-editor/gui/src/features/annotations/AnnotationView.tsx
- api-editor/gui/src/features/filter/FilterInput.tsx
Replace nested `p` elements by `span` elements.
> fix(gui): wrong nesting of HTML elements

- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
Closes #900 .
See Issue.
1. Load your Data into the api-editor
2. Select one parameter and look after 'Usages'
> feat:  usage information in selection view

- api-editor/gui/src/features/annotations/forms/BoundaryForm.tsx
Closes #870.
changed default value
create new boundary annotation, check default value
> feat(gui): boundaryform default value is now x >= 0, no upper limit

- api-editor/gui/src/features/packageData/model/PythonParameter.ts
- api-editor/gui/src/features/packageData/selectionView/ClassView.tsx
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/packageData/selectionView/ModuleView.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
- api-editor/gui/src/features/packageData/selectionView/UsageCounts.tsx
- api-editor/gui/src/features/usages/model/UsageCountStore.ts
* Show how often parameters are used explicitly vs. implicitly
* Show how often modules/classes/functions are used
> feat(gui): improve display of usages in selection view

- api-editor/gui/src/features/ui/uiSlice.ts
Closes #981.
* Add sensible default filter.
* Improve names of all default filters.
> feat(gui): `is:public !is:removed` as default filter

- package-parser/package_parser/processing/migration/model/_differ.py
Closes #1231.
add cache for compute_function_similarity and previous_function_similarity
use enhanced levenshtein distance from api wherever possible
run the migrate command and enjoy the shorter runtime
> feat: improve duration time of migration

- .github/dependabot.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- docs/requirements.txt
- mkdocs.yml
- package-lock.json
- package.json
- release.config.js
Closes #1273.
* Don't release when pushing to `main` anymore
* Instead release on demand
* Update a changelog on release and push the updated changelog to `main`
> ci: release on demand

- api-editor/build.gradle.kts
> build(deps): Bump Kotlin to v1.8.20

- api-editor/backend/build.gradle.kts
- api-editor/backend/src/main/kotlin/com/safeds/apiEditor/server/Application.kt
Remove dependencies that are no longer needed.
> build: remove outdated dependencies
