- api-editor/client/src/features/packageData/selectionView/DocumentationText.tsx
- package-parser/README.md
- package-parser/package_parser/commands/get_api/__init__.py
- package-parser/package_parser/commands/get_api/_ast_visitor.py
- package-parser/package_parser/commands/get_api/_model.py
- package-parser/package_parser/commands/get_dependencies/README.md
- package-parser/package_parser/commands/get_dependencies/_get_dependency.py
- package-parser/tests/commands/get_dependencies/test_get_dependency.py
Closes #131.
* package-parser now maintains newlines in description
* Update scikit-learn data
> fix: display of math blocks

- api-editor/client/src/common/MenuBar.tsx
- api-editor/client/src/features/packageData/model/PythonClass.ts
- api-editor/client/src/features/packageData/model/PythonDeclaration.ts
- api-editor/client/src/features/packageData/model/PythonFunction.ts
- api-editor/client/src/features/packageData/model/PythonParameter.ts
- api-editor/client/src/features/packageData/packageDataSlice.ts
- api-editor/client/src/features/packageData/selectionView/ClassView.tsx
- api-editor/client/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/client/src/features/packageData/selectionView/ParameterNode.tsx
- api-editor/client/src/features/packageData/treeView/ClassNode.tsx
- api-editor/client/src/features/packageData/treeView/FunctionNode.tsx
- api-editor/client/src/features/packageData/treeView/ModuleNode.tsx
- api-editor/client/src/features/packageData/treeView/TreeView.tsx
Closes #400.
* Don't show private declarations in tree view by default
* Add toggle in menu bar to show them anyway
* Always prevent annotating private API elements
* Add a marker `(private)` to private declarations in the details view
1. Check the functionality of the `Show private declarations` button in the menu bar
> feat: hide private declarations by default and prevent annotating them

- .flake8
* Deactivate some rules from flake8 that are handled already by other linters
> build: configure flake8

- api-editor/client/src/features/annotatedPackageData/model/AnnotatedPythonClass.ts
- api-editor/client/src/features/annotatedPackageData/model/AnnotatedPythonFunction.ts
- api-editor/client/src/features/annotatedPackageData/model/AnnotatedPythonModule.ts
- api-editor/client/src/features/annotatedPackageData/model/AnnotatedPythonPackage.ts
- api-editor/client/src/features/annotatedPackageData/model/AnnotatedPythonResult.ts
- api-editor/client/src/features/packageData/model/PythonClass.ts
- api-editor/client/src/features/packageData/model/PythonFilter.ts
- api-editor/client/src/features/packageData/model/PythonFromImport.ts
- api-editor/client/src/features/packageData/model/PythonFunction.ts
- api-editor/client/src/features/packageData/model/PythonImport.ts
- api-editor/client/src/features/packageData/model/PythonModule.ts
- api-editor/client/src/features/packageData/model/PythonPackage.ts
- api-editor/client/src/features/packageData/model/PythonParameter.ts
- api-editor/client/src/features/packageData/model/PythonResult.ts
* Use [parameter properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties) from TypeScript
> refactor: use TypeScript parameter properties

- package-parser/package_parser/commands/generate_annotations/generate_annotations.py
- package-parser/tests/commands/generate_annotations/test_generate_annotations.py
Closes #476.
* Don't create `@Unused` annotations for parameters anymore
1. Open a terminal in `package-parser`.
2. Run `parse-package generate -a .\tests\data\api_data.json -u .\tests\data\usage_data.json -o .\out\out.json`.
3. Ensure not `@Unused` annotations are created for parameters in `out\out.json`.
> fix: don't create `@Unused` annotations for parameters

- .github/workflows/main.yml
- package-parser/package_parser/commands/generate_annotations/generate_annotations.py
Closes #477.
* Fix possible `FileNotFoundError` during `generate` command
* Update smoke test to catch this issue
1. Open terminal in `package-parser` directory.
2. Run `parse-package generate -a .\tests\data\api_data.json -u .\tests\data\usage_data.json -o .\doesNotExistYet\out.json` where `doesNotExistYet` should, surprisingly, be a directory that does not exist yet.
> fix: `FileNotFoundError` during `generate` command

- .github/workflows/dependency-review.yml
Add a GitHub action that checks newly added dependencies in a PR for known vulnerabilities.
> ci: check added dependencies for vulnerabilities

- package-parser/package_parser/commands/generate_annotations/generate_annotations.py
- package-parser/package_parser/commands/get_api/_ast_visitor.py
- package-parser/package_parser/commands/get_api/_model.py
- package-parser/tests/commands/generate_annotations/test_generate_annotations.py
- package-parser/tests/commands/get_dependencies/test_get_dependency.py
- package-parser/tests/data/boundaries/api_data.json
- package-parser/tests/data/constants/api_data.json
- package-parser/tests/data/enums/api_data.json
- package-parser/tests/data/optionals/api_data.json
- package-parser/tests/data/requireds/api_data.json
- package-parser/tests/data/unuseds/api_data.json
Closes #449.
Added pname parameter to module, class, function and parameter api elements. pname parameter should be a qualified and unique pathname, unlike qname and name.
pname format: "package/module/class/function/parameter"
module can be: "module.name"
Execute:
parse-package api <package> <out> 
And check that the pname parameter is set for every module, class, function and parameter.
> refactor: Qualified and unique path "pname" variable added to most api elements

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGenerator.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/codegen/PythonDocstringGenerator.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/codegen/Util.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/ConstructorPythonCodeGeneratorFullPipelineTest.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/FunctionPythonCodeGeneratorFullPipelineTest.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/MethodPythonCodeGeneratorFullPipelineTest.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGeneratorTest.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/PythonDocstringGeneratorTest.kt
Closes #514.
Create docstrings for generate Python classes and functions if they contain any additional information.
1. Launch the backend:
```sh
cd api-editor
./gradlew run
```
2. Open the browser at [localhost:4280](http://localhost:4280).
3. Load some API data into the editor
4. Click "Generate adapters" in the menu bar
5. Extract the downloaded `.zip` file
6. Check the create Python files (`adapters` folder)
> feat: add docstrings in generated python code

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/validation/AnnotationValidator.kt
Closes #520.
* Don't throw an NPE if the map with possible combinations of annotations lacks an entry
* Add missing entries for `@Pure` annotation
1. Run the backend
```
cd api-editor
./gradlew run
```
2. Open localhost:4280 in the browser.
3. Add `@Pure`, `@CalledAfter`, `@Group`, `@Move`, `@Rename` annotations to the same API element.
4. Click on `Generate adapters`.
5. Check that a Zip file is being downloaded.
> fix: NPE if `@Pure` annotation is combined with another annotation

- api-editor/gui/src/features/packageData/PackageDataImportDialog.tsx
When importing new API data the filter input field was previously set to "". Now it's set to "is:public".
1. Run the backend:
```sh
cd api-editor
./gradlew run
```
2. Open localhost:4280 in the browser.
3. Import new API data
4. Check the content of the filter input field.
> fix: set filter to "is:public" after API data import

- .github/workflows/main.yml
- .github/workflows/pr.yml
- package-parser/README.md
- package-parser/package_parser/cli.py
- package-parser/package_parser/commands/get_api/_get_api.py
- package-parser/package_parser/commands/get_api/_package_metadata.py
- package-parser/poetry.lock
- package-parser/pyproject.toml
Closes #524.
* Stricter config for mypy (type hints were missing).
* Optionally pass path to API source to `api` and `all` commands.
* Remove `scikit-learn` dependency. To generate data for `scikit-learn` now, we can download the sources from [GitHub](https://github.com/scikit-learn/scikit-learn), for example.
* Use our own code as input for smoke tests, which makes them considerably faster than using `scikit-learn`.
1. Open the correct directory in a terminal:
```sh
cd package-parser
```
2. Run the `api` command:
```sh
poetry run parse-package api -p package_parser -s package_parser -o out
```
3. Run the `all` command:
```sh
poetry run parse-package all -p package_parser -s package_parser -c package_parser -o out
```
4. Check that everything ran correctly.
> feat: pass path of API sources to `api` command

- package-parser/package_parser/commands/get_api/_ast_visitor.py
Closes #525.
Add missing slashes to the created `pname` properties.
1. Run
```sh
cd package-parser
poetry run parse-package api -p package_parser -s package_parser -o out
```
2. Check the `pname` properties.
> fix: incorrect pnames

- package-parser/package_parser/commands/get_api/_refined_types.py
- package-parser/tests/commands/get_api/test_boundaries.py
Create boundary types even if one of the bounds was negative.
1. Create API data for scikit-learn
```sh
poetry run parse-package api -p sklearn -o out
```
2. Ensure that boundary types are created even if the bounds are negative
> fix: create boundary type for negative bound

- api-editor/gui/src/features/annotations/forms/CalledAfterForm.tsx
- api-editor/gui/src/features/annotations/forms/EnumForm.tsx
- api-editor/gui/src/features/annotations/forms/GroupForm.tsx
- api-editor/gui/src/features/annotations/forms/MoveForm.tsx
- api-editor/gui/src/features/annotations/forms/RenameForm.tsx
Closes #593.
Opening an annotation form that sets the focus to some input element could crash the application. This  happens due to a possible race condition between calling `reset` and `setFocus`.
1. Add a `@calledAfter` annotation to a function
2. Add a `@group` annotation to a function
3. Add a `@rename` annotation to an API element
4. Add a `@move` annotation to a global API element
5. Add a `@enum` annotation to a parameter.
The app should no longer crash in these cases.
> fix: crash when some annotation forms were opened

- .gitignore
- package-parser/README.md
- package-parser/package_parser/cli/_cli.py
Closes #608.
Verbose output can now be enable in the Python CLI commands like so:
```sh
parse-package -v api ...
```
Note that the `-v` flag must be between `parse-package` and any subcommand like `api`.
> feat: verbose flag

- .flake8
- .github/workflows/main.yml
- .github/workflows/pr.yml
- package-parser/README.md
- package-parser/package_parser/cli/_cli.py
- package-parser/package_parser/cli/_run_all.py
- package-parser/package_parser/cli/_run_usages.py
- package-parser/package_parser/processing/usages/_ast_visitor.py
- package-parser/package_parser/processing/usages/_find_usages.py
- package-parser/package_parser/utils/__init__.py
- package-parser/package_parser/utils/_parsing.py
Closes #607.
* We no longer create another file to hold the usage counts for each file with client code. The reading and writing was time intensive and it was hard to get rid of the 30k+ files afterwards.
* Workaround a memory leak caused by the internal caching of `astroid`. Previously, the memory usage would continually increase until all RAM was used, heavily slowing down the system. In many cases, a PC restart was necessary. Unfortunately, there is no satisfactory way to disable/clear the caches. Therefore, we kill the Python processes once they are done with their batch and start new ones. This leads to the jigsaw pattern regarding memory usage shown in the second screenshot below.
* Add CLI argument `--processes` and `--batchsize` to control the tradeoff between performance and …
> perf: improve performance of usage command

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/mutable_model/PythonAst.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/server/Routing.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/transformation/ParameterAnnotationProcessor.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGeneratorTest.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/transformation/ParameterAnnotationProcessorTest.kt
Closes #616.
Adding the `@Constant` (or `@Optional`/`@Attribute`) annotations with value `None` to multiple parameters caused a NPE in the backend when generating adapters. This was caused because the AST node `PythonNone` was a singleton and was, therefore, always moved to the last place were it was needed. The previous places were set to `null`. 
**Note for the future:** Do not create singleton `PythonAstNode`s!
> fix: NPE when generating adapters with multiple annotations with default value `None`

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/server/Routing.kt
- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/transformation/TransformationPlan.kt
- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/common/DeleteAllAnnotations.tsx
- api-editor/gui/src/common/GenerateAdapters.tsx
- api-editor/gui/src/common/MenuBar.tsx
Closes #581.
When user clicks on "Generate Adapters" a dialog will appear where the user can enter the name of the generated package.
> feat: configure name of generated package

- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
- api-editor/gui/src/features/packageData/selectionView/SelectionView.tsx
Remove the gap between the info about the selected declaration and the action bar in the selection view. Notice how the scroll bar in the screenshot below now touches the border of the action bar.
> fix(gui): remove gap between info and action bar in selection view

- api-editor/gui/src/features/packageData/treeView/TreeNode.tsx
- api-editor/gui/src/features/packageData/treeView/VisibilityIndicator.tsx
Closes #624.
Change the user interaction with nodes in the tree view:
1. If the user clicks on the visibility indicator (down/right arrow), the node is only expanded/collapsed but not selected.
2. If the user clicks on another part of the node with `Shift` pressed, the node is also only expanded/collapsed but not selected.
3. Otherwise, the node is selected but not expanded.
> feat(gui): select but don't expand/collapse in tree view

- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
- api-editor/gui/src/features/packageData/selectionView/SelectionView.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #588.
The button "Expand Matched" expands/collapses nodes in the tree view so that as few nodes as possible but all matched nodes are visible.
> feat(gui): button to expand tree view up to matched nodes

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGenerator.kt
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/codegen/PythonCodeGeneratorTest.kt
Previously, a multi-line TODO comment would lead to erroneous Python code. This is fixed now.
> fix(backend): syntax of multi-line todo comment

- api-editor/gui/src/features/annotations/AnnotationDropdown.tsx
- api-editor/gui/src/features/annotations/AnnotationImportDialog.tsx
- api-editor/gui/src/features/annotations/AnnotationView.tsx
- api-editor/gui/src/features/annotations/DoneButton.tsx
- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/packageData/selectionView/ClassView.tsx
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
Closes #591.
* Add new meta-annotation "done". This can be used to express that an API element is completely annotated and all annotations are checked.
* Disable annotation dropdown when an element is done.
* Disable annotation view when an element is done.
> feat(gui): mark entire API elements as done

- api-editor/gui/src/common/FilterHelpButton.tsx
- api-editor/gui/src/common/FilterInput.tsx
- api-editor/gui/src/features/packageData/model/filters/AnnotationFilter.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
Closes #589.
Add new filter `is:done`. Even though the "done" marker is implemented as an annotation, we use a special token for it, since we want to hide this implementation detail from the user.
> feat(gui): add `is:done` filter

- api-editor/gui/src/features/annotations/AnnotationImportDialog.tsx
- api-editor/gui/src/features/annotations/annotationSlice.ts
Closes #636.
Users can now decide to merge imported annotations into the existing ones or replace the existing ones completely.
> feat(gui): merge annotations on import

- api-editor/gui/src/features/usages/UsageImportDialog.tsx
- api-editor/gui/src/features/usages/model/UsageCountStore.ts
Closes #612.
The GUI did not take implicit usages of default value into account when computing the usefulness of parameters. This meant we would either get the usefulness correct if the default value was the most common value or estimate a too low value if it was not.
The remaining matches are correct and due to the fact that no `@constant` annotations are created if their default value is not a literal.
> fix(gui): add implicit usages of default values on import

- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/treeView/HeatMapTag.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #587.
Allow sorting of the tree view by usages in descending order.
> feat(gui): sort classes/functions by usages

- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/model/filters/UsageFilter.ts
- api-editor/gui/src/features/packageData/model/filters/UsefulnessFilter.ts
- api-editor/gui/src/features/packageData/treeView/ClassNode.tsx
- api-editor/gui/src/features/packageData/treeView/FunctionNode.tsx
- api-editor/gui/src/features/packageData/treeView/HeatMapTag.tsx
- api-editor/gui/src/features/packageData/treeView/ModuleNode.tsx
- api-editor/gui/src/features/packageData/treeView/ParameterNode.tsx
- api-editor/gui/src/features/usages/model/UsageCountStore.ts
Closes #640.
* Define module usages as the sum of usages of classes/functions in the module
* Define module usefulness as equal to module usages
* Display heat map tags for module usages/usefulness
* Filters `usages:...` and `usefulness:...` now affect modules
* Sorting by usages now also affects modules
> feat(gui): module usages/usefulness

- api-editor/gui/src/app/App.tsx
Closes #657.
The action bar now spans the full width of the screen rather than just the right pane.
> feat(gui): action bar spanning full width of screen

- api-editor/gui/src/common/FilterHelpButton.tsx
- api-editor/gui/src/features/annotations/AnnotationDropdown.tsx
- api-editor/gui/src/features/annotations/AnnotationView.tsx
- api-editor/gui/src/features/annotations/CompleteButton.tsx
- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/packageData/model/filters/AnnotationFilter.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
- api-editor/gui/src/features/packageData/selectionView/ClassView.tsx
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
API elements can now be marked as "complete" rather than "done". The semantics are that no further annotations need to be added to this element. Therefore, it also only prevents adding new annotations. Existing annotations can still be edited.
> feat(gui): change "done" to "complete"

- api-editor/gui/src/features/packageData/model/filters/filterFactory.test.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
Closes #669.
`annotation:@calledAfter` works now.
> fix(gui): `annotation:@calledAfter` not seen as valid filter

- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
Closes #666. 😈
The headings of parameters in the selection view of functions can now be clicked to go to the full selection view of the corresponding parameter.
> feat(gui): link from selection view of function to its parameters

- api-editor/gui/src/features/packageData/selectionView/ActionBar.tsx
Closes #672.
* Add a button to the action bar to go to the parent of the selected element. It can also be activated by pressing `Alt+U` (up).
* Add missing keyboard shortcuts: `Alt+P` for previous, `Alt+N` for next.
> feat(gui): go to parent

- api-editor/gui/src/features/annotations/batchforms/DestinationBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/OldNewBatchForm.tsx
Closes #675.
Show the validation messages of the input fields in the forms for batch rename and batch move.
> feat(gui): show validation messages in form of batch rename and move

- api-editor/gui/src/features/packageData/treeView/TreeNode.tsx
Closes #680.
Collapse all descendent nodes when the root of a subtree is collapsed.
> fix(gui): properly collapse subtree in tree view

- api-editor/gui/src/common/FilterHelpButton.tsx
- api-editor/gui/src/features/packageData/model/filters/AbstractPythonFilter.test.ts
- api-editor/gui/src/features/packageData/model/filters/NameRegexFilter.ts
- api-editor/gui/src/features/packageData/model/filters/NameStringFilter.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.test.ts
- api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
Closes #682.
* Change `name:xy` to `name:~xy` (substring matching)
* `name:~xy` is now case-sensitve
* Add `name:=xy` for exact matching of the name (also case-sensitive)
* Add `name:/xy/ to match the name by a regex
* Change `usages:20` to `usages:=20`
* Change `usefulness:20` to `usefulness:=20`
> feat(gui): more ways to filter by name

- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/packageData/selectionView/SelectionView.tsx
- api-editor/gui/src/features/packageData/selectionView/StatisticsView.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #646.
* Display statistics in third column
* Clean up annotation statistics
* Move annotation statistics to top (dynamic information)
> feat(gui): separate column for statistics

- .github/workflows/main.yml
- api-editor/backend/build.gradle.kts
- release.config.js
The built JAR should now be attached to a release.
> ci: fix failing asset upload

- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
Set a maximum width on the chart that display the values of parameters. Otherwise, it would be too prominent on bigger screens.
> fix(gui): maximum width for parameter value chart

- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/common/DeleteAllAnnotations.tsx
- api-editor/gui/src/common/MenuBar.tsx
Closes #694.
Users can no longer delete all annotations or use the batch mode when the username is invalid or becomes invalid when they use these features.
> fix(gui): disable "batch mode" and "delete all annotations" when username is invalid

- api-editor/gui/src/features/statistics/AnnotationStatistics.tsx
- api-editor/gui/src/features/statistics/ProgressStatistics.tsx
Closes #693.
We now only count annotations on elements that are matched by the current filter in the annotation statistics.
This way the sum of the counts displayed in the annotation statistics is equal to the sum of "correct" and "incorrect?" annotations displayed in the review progress. Moreover, for non-repeatable annotations, clicking the corresponding button should change the filter so that exactly as many matches are remaining as was previously displayed on the button.
> feat(gui): count annotations only on matched elements

- api-editor/gui/src/features/filter/FilterHelpButton.tsx
- api-editor/gui/src/features/filter/model/QualifiedNameRegexFilter.ts
- api-editor/gui/src/features/filter/model/QualifiedNameStringFilter.ts
- api-editor/gui/src/features/filter/model/filterFactory.ts
- api-editor/gui/src/features/packageData/model/PythonClass.ts
- api-editor/gui/src/features/packageData/model/PythonDeclaration.ts
- api-editor/gui/src/features/packageData/model/PythonFunction.ts
- api-editor/gui/src/features/packageData/model/PythonModule.ts
- api-editor/gui/src/features/packageData/model/PythonPackage.ts
- api-editor/gui/src/features/packageData/model/PythonParameter.ts
- api-editor/gui/src/features/packageData/model/PythonResult.ts
Closes #696.
* New filter `qname:=[string]` to match an exact qualified name
* New filter `qname:~[string]` to match elements that have the `[string]` in their qualified name
* New filter `qname:/[regex]/` to match elements with a qualified name that matches the `[regex]`
> feat(gui): filter by qualified name

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/server/Application.kt
- api-editor/backend/src/main/resources/application.conf
- api-editor/backend/src/test/kotlin/com/larsreimann/api_editor/server/ApplicationTest.kt
Allow configuration of backend server to be overwritten by command line arguments. This is particularly useful to run multiple instances of the program at once on separate ports. See [Ktor documentation](https://ktor.io/docs/configurations.html#command-line) for details.
> feat(backend): change server config via command line arguments

- api-editor/gui/src/features/annotations/batchforms/ConfirmAnnotations.tsx
- api-editor/gui/src/features/annotations/batchforms/DestinationBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/OldNewBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/TypeValueBatchForm.tsx
Closes #734.
Batch rename can now be used to replace a substring of the name with an empty string.
> feat(gui): enable batchmode rename to replace with an empty string

- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
Closes #757.
Instead of comparing a string with some self-made regex to figure out whether represents a number literal, we now try to parse the string as a float. If this is successful, we treat it as a number literal.
Parameter value distribution of `#/sklearn/sklearn.linear_model._coordinate_descent/ElasticNetCV/__init__/eps`:
> fix(gui): detect numbers using scientific notation as literals

- api-editor/gui/src/features/annotations/annotationSlice.ts
Closes #728.
Add new state to undo/redo history after marking an element as complete or an annotation as correct. On the one hand this allow to undo/redo these changes individually. More importantly, however, undoing no longer undoes all "Mark as Complete"/"Mark as Correct" that have been done since the last change to/addition of an annotation.
> feat(gui): undo/redo for "Mark as Complete" and "Mark as Correct"

- api-editor/gui/src/common/util/stringOperations.test.ts
- api-editor/gui/src/common/util/stringOperations.ts
- api-editor/gui/src/features/annotations/AnnotationView.tsx
Closes #718.
Up to 50 characters of the message of a `@Todo` annotation are now shown without having to edit the annotation.
> feat(gui): preview message of `@Todo` annotation

- api-editor/gui/src/common/MenuBar.tsx
Closes #735.
After the user has chosen an option in the batch mode dropdown (menu bar) the dropdown is now closed properly.
> fix(gui): close batch mode dropdown after an option was chosen

- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
Closes #753.
Use `UnorderedList` component from `chakra` when rendering MarkDown lists.
> fix(gui): bullet point overlapping with "read more/less" icon button

- api-editor/gui/src/features/actionBar/ActionBar.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/treeView/TreeView.tsx
Closes #752.
The previous/next buttons should now behave correctly if an element is selected that no longer appears in the filtered tree view.
> fix(gui): previous/next if selected element not appear in filtered tree view

- api-editor/gui/src/common/MenuBar.tsx
- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
- api-editor/gui/src/features/ui/uiSlice.ts
Closes #770.
There is a new setting "Expand Documentation by Default" in the menu bar. When this is switched on, all documentation texts are expanded already when a new element is selected. **Important:** This does not affect the selection view that is already opened when the setting is changed.
> feat(gui): option to expand documentation by default

- api-editor/gui/src/features/packageData/selectionView/ClassView.tsx
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/packageData/selectionView/ModuleView.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
Closes #725.
Any API element can now be marked as complete, even if no annotations can be added to it yet. Compared to before, it is now also possible to mark the following API elements as complete:
* Modules
* Internal classes
* Internal functions
* Internal parameters
* Implicit parameters
> feat(gui): mark any API element as complete

- api-editor/gui/src/features/statistics/AnnotationStatistics.tsx
Closes #748.
* New button in annotation statistics to clear annotation filter
* New button in annotation statistics to show elements with any annotation
* Minor improvements to how the buttons affect whitespace in the filter string
> feat(gui): improve annotation filter buttons in statistics view

- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/menuBar/MenuBar.tsx
Closes #737.
The completion status of the selected API element can now be toggled by `Ctrl+Alt+C`. When a function is selected only its own completion status is affected, not the one of its parameters.
> feat(gui): shortcut to toggle completion of selected element

- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
- api-editor/gui/src/features/statistics/ChartWrappers.tsx
Closes #720.
When the cursor hovers over a bar chart the tooltip of the bar with the closest y-coordinate is now always shown. This allows to view the tooltip easily even for tiny bars without having to be pixel-perfect with the mouse.
> fix(gui): show tooltips on bar charts even when cursor does not intersect bar

- api-editor/gui/package-lock.json
- api-editor/gui/package.json
- api-editor/gui/src/features/annotations/AnnotationView.tsx
- api-editor/gui/src/features/annotations/MissingAnnotationButton.tsx
- api-editor/gui/src/features/menuBar/HelpMenu.tsx
- api-editor/gui/src/features/menuBar/MenuBar.tsx
- api-editor/gui/src/features/packageData/selectionView/ClassView.tsx
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
- api-editor/gui/src/features/reporting/issueURLBuilder.test.ts
- api-editor/gui/src/features/reporting/issueURLBuilder.ts
Closes #730.
* "Help" menu where users can report generic bugs/request features
* Button besides all annotation dropdowns to report missing annotations
* Button besides all annotation tags to report wrong annotations
Unfortunately, when flagging a wrong annotation, the dropdown "Actual Annotation Type" is not pre-filled. This does not seem to be possible at the moment (https://github.com/github-community/community/discussions/5288).
> feat(gui): improved issue reporting

- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/annotations/batchforms/RequiredBatchForm.tsx
Closes #7498.
When a `@Attribute`/`@Constant`/`@Optional`/`@Required` annotation is added to an element, it now replaces any existing `@Attribute`/`@Constant`/`@Optional`/`@Required` annotation on this element.
> feat(gui): attribute/constant/optional/required annotations now replace each other

- api-editor/gui/src/features/menuBar/SelectionBreadcrumbs.tsx
- api-editor/gui/src/features/packageData/model/PythonDeclaration.ts
- api-editor/gui/src/features/packageData/selectionView/ClassView.tsx
- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
- api-editor/gui/src/features/packageData/selectionView/FunctionView.tsx
- api-editor/gui/src/features/packageData/selectionView/ParameterNode.tsx
Closes #95.
Links to other modules/classes/global functions are now detected in the documentation. If it is possible to resolve them, they are replaced by actual links. Otherwise, we replace them by the name of the referenced declaration.
> feat(gui): links to other declarations in documentation

- api-editor/gui/src/app/App.tsx
- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
The documentation text now gets its own scrollbar when the text overflows the middle pane.
> fix(gui): scrollbars on documentation text

- api-editor/gui/src/features/reporting/issueURLBuilder.ts
When the user clicks the button to report a wrong annotation the created issue now automatically gets the label for the wrong annotation. The user can (and should) still add further labels if the expected annotation differs.
> feat(gui): prefill label for GitHub issue for wrong annotation

- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
The qualified name of the selected declaration was used as the label of relative links in the documentation. Now it's correctly the qualified name of the linked declaration.
> fix(gui): wrong label for relative links in documentation

- api-editor/gui/src/features/annotations/AnnotationDropdown.tsx
Group annotations in the annotation dropdown together if they have a similar purpose. Currently, this only affects annotations of parameters. For classes and functions the annotations are all quite distinct from each other.
> feat(gui): categorize annotations in annotation dropdown

- api-editor/gui/src/features/annotations/AnnotationView.tsx
- api-editor/gui/src/features/annotations/MissingAnnotationButton.tsx
- api-editor/gui/src/features/annotations/batchforms/AnnotationBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/ConstantBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/DestinationBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/EmptyBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/MoveBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/OldNewBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/OptionalBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/RemoveBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/RenameBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/RequiredBatchForm.tsx
- api-editor/gui/src/features/annotations/batchforms/TypeValueBatchForm.tsx
- api-editor/gui/src/features/annotations/forms/AnnotationForm.tsx
- api-editor/gui/src/features/annotations/forms/AttributeForm.tsx
- api-editor/gui/src/features/annotations/forms/BoundaryForm.tsx
- api-editor/gui/src/features/annotations/forms/CalledAfterForm.tsx
- api-editor/gui/src/features/annotations/forms/ConstantForm.tsx
- api-editor/gui/src/features/annotations/forms/DescriptionForm.tsx
- api-editor/gui/src/features/annotations/forms/EnumForm.tsx
- api-editor/gui/src/features/annotations/forms/GroupForm.tsx
- api-editor/gui/src/features/annotations/forms/MoveForm.tsx
- api-editor/gui/src/features/annotations/forms/OptionalForm.tsx
- api-editor/gui/src/features/annotations/forms/RenameForm.tsx
- api-editor/gui/src/features/annotations/forms/TodoForm.tsx
- api-editor/gui/src/features/annotations/forms/TypeValueForm.tsx
- api-editor/gui/src/features/externalLinks/urlBuilder.test.ts
- api-editor/gui/src/features/externalLinks/urlBuilder.ts
- api-editor/gui/src/features/menuBar/HelpMenu.tsx
- api-editor/gui/src/features/menuBar/MenuBar.tsx
Closes #745.
* Link to user guide (thanks to @Aclrian) on GitHub
* Add short help texts to annotation forms that describe the effect of annotations
I'm still looking for a good place to add help texts to annotations that don't require further inputs and, thus, don't have an accompanying form.
> feat(gui): descriptions of annotations

- api-editor/gui/src/features/annotations/AnnotationImportDialog.tsx
- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/menuBar/HelpMenu.tsx
- api-editor/gui/src/features/packageData/PackageDataImportDialog.tsx
- api-editor/gui/src/features/packageData/apiSlice.ts
- api-editor/gui/src/features/packageData/model/PythonPackageBuilder.ts
- api-editor/gui/src/features/ui/uiSlice.ts
- api-editor/gui/src/features/usages/UsageImportDialog.tsx
- api-editor/gui/src/features/usages/model/UsageCountStore.ts
- api-editor/gui/src/features/usages/usageSlice.ts
- data/annotations/sklearn__annotations.json
- data/usages/sklearn__usage_counts.json
- package-parser/package_parser/model/annotations/__init__.py
- package-parser/package_parser/model/annotations/_annotations.py
- package-parser/package_parser/model/api/__init__.py
- package-parser/package_parser/model/api/_api.py
- package-parser/package_parser/model/usages/__init__.py
- package-parser/package_parser/model/usages/_usages.py
- package-parser/tests/model/test_annotations.py
- package-parser/tests/model/test_usages.py
Closes #714.
* Add versions to API/annotation/usages files
* Don't allow importing outdated files
* Bust the IndexedDB cache if it contains outdated data
> feat: versioning for json data

- .github/ISSUE_TEMPLATE/missing_annotation.yml
- .github/ISSUE_TEMPLATE/wrong_annotation.yml
Closes partially #807.
The issue templates for missing/wrong annotations now have to additional optional fields where users can enter contextual information about the API data and the usage data they have loaded.
> chore: fields for minimal API data and minimal usage store in issue templates

- api-editor/backend/src/main/kotlin/com/larsreimann/api_editor/mutable_model/PythonAst.kt
The implementation was missing previously. Since it's never used yet anyway, this PR is not marked as a fix.
> chore(backend): override children() on PythonNamedSpread and PythonPositionalSpread

- api-editor/gui/src/features/annotations/annotationSlice.ts
- api-editor/gui/src/features/menuBar/DeleteAllAnnotations.tsx
Importing and merging an incomplete annotation file no longer crashes the application.
> fix(gui): crash when importing incomplete annotation files

- api-editor/gui/src/features/packageData/PackageDataImportDialog.tsx
Previously, simply selecting an API file in the import dialog for package data would delete all annotations. Now this only happens when the user actually clicks on submit.
> fix(gui): deletion of all annotations when user selects API file in import dialog

- api-editor/gui/src/features/filter/model/AnnotationFilter.ts
Due to another regression introduced in #796, annotation filters were matching elements with removed autogenerated annotations. This PR fixes this.
> fix(gui): annotation filters matching element if it had removed autogenerated annotations

- api-editor/gui/src/features/annotations/batchforms/AnnotationBatchForm.tsx
- api-editor/gui/src/features/annotations/forms/AnnotationForm.tsx
Closes #845.
Annotation forms and annotation batch forms can now be confirmed using `Ctrl+Enter` and cancelled using `Esc`.
> feat(gui): keyboard shortcuts for annotation forms

- package-parser/package_parser/processing/annotations/_generate_enum_annotations.py
- package-parser/tests/data/enums/annotation_data.json
- package-parser/tests/data/enums/api_data.json
Closes #858.
For string values like "SAMME.R" we now create the enum instance name "SAMME_R" rather than "SAMMER".
> feat(parser): replace dots with underscores for enum instance names

- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
Closes #865.
External links in the documentation should now be rendered properly.
> fix(gui): external links in documentation

- api-editor/gui/src/features/annotations/AnnotationView.tsx
Closes #841.
When the user clicks on "Mark as Correct" the annotation form for exactly this annotation is now hidden. If another annotation is currently being edited, nothing happens.
> feat(gui): close annotation form when corresponding annotation is marked as correct

- api-editor/gui/src/features/menuBar/MenuBar.tsx
On startup the navigate menu and associated shortcuts were wrongly disabled.
> fix(gui): navigate menu disabled on startup

- package-parser/package_parser/processing/api/_package_metadata.py
- package-parser/poetry.lock
- package-parser/pyproject.toml
`importlib-metadata` is no longer required for Python 3.10.
> build(deps): remove importlib-metadata polyfill

- package-parser/package_parser/processing/api/documentation_parsing/_NumpyDocParser.py
- package-parser/tests/processing/api/documentation/test_NumpyDocParser.py
Previously, whitespace was removed from start and end of each line if the description. This removed any indentation, which is needed to detect code blocks (#827). Now only whitespace at the end of a line is removed.
> fix(parser): indentation of description

- api-editor/gui/package-lock.json
- api-editor/gui/package.json
- api-editor/gui/src/features/filter/FilterInput.tsx
- api-editor/gui/src/features/filter/model/filterFactory.ts
Closes #837.
When the user inputs an incorrect filter, a possible replacement gets suggested, provided a fixed filter exists with a Levenshtein distance of at most 3. The user can click on this suggestion to update the filter string.
> feat(gui): suggest replacement for wrong filter tokens

- data/annotations/sklearn__annotations.json
- package-parser/package_parser/processing/annotations/_generate_value_annotations.py
- package-parser/poetry.lock
- package-parser/pyproject.toml
- package-parser/tests/data/valueAnnotations/annotation_data.json
- package-parser/tests/data/valueAnnotations/api_data.json
- package-parser/tests/data/valueAnnotations/usage_data.json
Closes #912.
Closes #842.
Closes #828.
Closes #822.
By default we want to make a parameter constant, provided there is only one value and it's a literal. This part is unchanged.
If we cannot make the parameter constant, we now try to make a parameter required. If the most common value is not a literal, we always do so. Otherwise, we check how often the most common and the second most common value occur. Our null hypothesis is that they are equally likely to be chosen. Unless this hypothesis is rejected, we make the parameter required. If the hypothesis is rejected, we make the parameter optional. We reject the hypothesis if the probability that the observed values or even more extreme differences are produced, assuming our null hypothesis is true, is at most 5%.
On the `sklearn` data this …
> feat(parser): differentiate between required and optional parameters using statistical hypothesis testing

- api-editor/gui/src/features/annotations/AnnotationImportDialog.tsx
- api-editor/gui/src/features/annotations/versioning/migrations.ts
- api-editor/gui/src/features/menuBar/MenuBar.tsx
* Store schema version in exported annotation file
* Default schema version to 1 if it's not specified in the annotation file
> fix(gui): import of annotation files without schema version

- api-editor/gui/src/features/filter/model/DoneFilter.ts
- api-editor/gui/src/features/menuBar/MenuBar.tsx
Closes #938.
Fix a crash caused by the `is:done` filter.
> fix(gui): `is:done` filter crashes app

- api-editor/gui/src/features/annotations/AnnotationView.tsx
Closes #910.
Closes #911.
See these issues.
Import autogenerated Annotations and create/edit annotations.
View the icons on the right side of the annotation-button.
> feat(gui): Added a user icon for annotations which where added by the current user

- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
Closes #903.
Links to Methods are now being properly displayed as actual links instead of :meth:<name>.
Open api-editor with api and usage data for sklearn.
Open #/sklearn/sklearn.decomposition._pca/PCA and click on the link in the description (for class test).
Open #/sklearn/sklearn.preprocessing._encoders/OneHotEncoder/__init__/handle_unknown (for method test).
> feat(gui): implements links to methods in element description

- api-editor/gui/src/features/packageData/treeView/HeatMapTag.tsx
Closes #930.
Added a minimal width to the HeatMapTag so it doesn't shrink with long qnames or a narrow site.
Open api editor and load api and usages data for sklearn.
Enable a HeatMapMode and see if the HeatMapTag shrinks, when the page shrinks.
> feat(gui): set minWidth for HeatMapTag

- api-editor/gui/src/features/packageData/selectionView/ParameterView.tsx
Restore the colors for the parameter value histogram that were introduced in #937 and overwritten in #947.
> fix(gui): parameter value histogram is now transparent again

- api-editor/gui/src/app/App.tsx
The statistics view can no longer be resized. This interaction was not intended initially and was hard to use and buggy.
> fix(gui): statistics view can now no longer be resized

- api-editor/gui/src/features/filter/FilterControls.tsx
- api-editor/gui/src/features/filter/FilterInput.tsx
- api-editor/gui/src/features/filter/FilterPersistence.tsx
Closes #958.
We no longer update the global filter string after each keystroke in the filter input box. Instead, we only do so if the user stops typing for at least 1s. This drastically improves the responsiveness of the application while using the filter. Filter validation now happens on the local filter string, so the user still gets instant feedback about incorrect tokens.
> perf(gui): only change global filter string if user stops typing for 1s

- api-editor/gui/src/features/annotations/annotationSlice.ts
Closes #964.
A review from someone else can now be undone by a single click instead of two click.
> fix(gui): only click once to undo annotation review

- api-editor/gui/src/features/filter/FilterHelpButton.tsx
- api-editor/gui/src/features/filter/model/RemovedFilter.ts
- api-editor/gui/src/features/filter/model/filterFactory.ts
Closes #962.
Add a new filter `is:removed`. This only keeps elements that have the annotation `@remove` or that have an ancestor with this annotation. Annotations are only taken into consideration if they are neither removed nor marked as wrong.
> feat(gui): new filter `is:removed`

- data/annotations/sklearn__annotations.json
- package-parser/package_parser/processing/annotations/_generate_enum_annotations.py
- package-parser/tests/data/enumAnnotations/annotation_data.json
Closes #966.
If we detect that a parameter has a union type, we no longer create an `@enum` annotation for it.
> fix(parser): don't create enums for union types

- api-editor/gui/src/features/annotations/forms/GroupForm.tsx
- api-editor/gui/src/features/packageData/selectionView/DocumentationText.tsx
Closes #963.
If available, the descriptions of parameters are now shown in the group forms. This should make it easier to decide which parameters belong to a group.
> feat(gui): show parameter descriptions in group form

- api-editor/gui/package-lock.json
- api-editor/gui/package.json
- api-editor/gui/src/features/annotations/annotationSlice.ts
Closes #967.
When a user clicks on "Save" in an annotation form he is now only added as an author when the annotation was actually changed. Changing the comment is not enough. This is relevant for the quality view to detect annotations that were changed.
> feat(gui): only add author when annotation was actually changed

- api-editor/gui/src/features/packageData/treeView/TreeNode.tsx
Closes #984.
Tree nodes can now be toggled by double clicking instead of using `Shift+Click`. While this is more intuitive, it also introduces a slight delay before an item is selected, since we need to make sure the user does not double click the node. We'll see how this works out and potentially revert this change.
> feat(gui): toggle tree nodes by double-clicking

- api-editor/gui/src/features/annotations/AnnotationView.tsx
- api-editor/gui/src/features/annotations/CompleteButton.tsx
Closes #988.
Tooltips are now also shown on the following buttons when they are disabled:
* Complete
* Remove annotation
* Edit annotation
* Mark as Correct
* Mark as Unsure
* Mark as Wrong
* Correct
* Unsure
* Wrong
> fix(gui): tooltips for disabled buttons in annotation view

- .editorconfig
The `disabled_rules` property was deprecated.
> chore: change disable_rules to ktlint_disabled_rules

- package-parser/README.md
- package-parser/package_parser/cli/_cli.py
- package-parser/package_parser/cli/_run_migrate.py
Closes #1108.
Created a migrate cli command, that takes two api files, an annotation file, and an output path as input
Run Terminal with `parse-package migrate -a1 apiv1.json -a2 apiv2.json -a annotations.json -o out`
> feat: Create command line interface for a migrate command

- .mypy.ini
- package-parser/pyproject.toml
* Move `mypy` config to top level
* Fix incorrect names of options
> ci: fix mypy config

- package-parser/package_parser/processing/annotations/model/_AnnotationStore.py
- package-parser/package_parser/processing/migration/_migrate.py
- package-parser/package_parser/processing/migration/annotations/__init__.py
- package-parser/package_parser/processing/migration/annotations/_migrate_boundary_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_enum_annotation.py
- package-parser/tests/processing/migration/annotations/test_boundary_migration.py
- package-parser/tests/processing/migration/test_migration.py
Closes #1142.
- add migration for `@boundary` annotations to another version, with the possibilities:
- If the mapped parameter has a number boundary and its type is known, the annotation will be migrated as expected. The interval would be converted if the type of the parameter from apiv1 and the type of the parameter from apiv2 mismatch (int, float). From a floating point boundary to an integer boundary, the boundary would be smaller. E.g., The interval (0.5, 9.5) will be converted to [1, 9]. If a conversion happens, the migrated annotation will be marked as unsure.
-  If the mapped parameter is a parameter, but its type in unknown, an unsure boundary annotation will be created for this parameter, but without any conversion.
- If the element is not a parameter, a `@todo` annotation will …
> feat: migrate `@boundary` annotation

- package-parser/package_parser/processing/annotations/model/_annotations.py
- package-parser/package_parser/processing/migration/_migrate.py
- package-parser/package_parser/processing/migration/annotations/__init__.py
- package-parser/package_parser/processing/migration/annotations/_migrate_boundary_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_enum_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_rename_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_value_annotation.py
- package-parser/tests/processing/migration/annotations/test_boundary_migration.py
- package-parser/tests/processing/migration/annotations/test_value_migration.py
- package-parser/tests/processing/migration/test_migration.py
Closes #1145.
- add migration for `@value` annotations to another version, with the possibilities:
- If the variant of the annotation is omitted and both parameter have the same value, the annotation will be migrated as expected. If the type is different, the annotation will be marked as unsure.
- If the variant of the annotation is required and the parameter from apiv2 has a default value of the same type, the annotation will be migrated as expected.
- If the variant is optional or constant and the type of the parameter from apiv2 is known and the type of the parameters match, an annotation will be migrated as expected. If the type is unknown, the annotation will be marked as unsure.
run the migrate command or view and run the `test_migration.py` file
> feat: migrate `@value` annotation

- package-parser/package_parser/processing/migration/_migrate.py
- package-parser/package_parser/processing/migration/annotations/_get_annotated_api_element.py
- package-parser/package_parser/processing/migration/annotations/_migrate_move_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_remove_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_todo_annotation.py
- package-parser/package_parser/processing/migration/annotations/_migrate_value_annotation.py
- package-parser/tests/processing/migration/annotations/test_move_annotation.py
- package-parser/tests/processing/migration/annotations/test_remove_migration.py
- package-parser/tests/processing/migration/test_migration.py
Closes #1144.
- Migration of `@remove` annotations through a mapping from old api elements to new api elements.
If the mapped apiv2 element is removable (a class or function), change the target of the annotation.
Otherwise, mark the api element that are not removable with an `@todo` annotation.
- New methods `get_annotated_api_element` and `get_annotated_api_element_by_type` to get the element from an annotation by its id.
run the migrate command or view and run the `test_migration.py` file
> feat: add `@remove` migration

- package-parser/package_parser/processing/api/model/_types.py
- package-parser/package_parser/processing/migration/model/_differ.py
- package-parser/poetry.lock
- package-parser/pyproject.toml
Closes ##1179.
add dependecy levenshtein and use its distance function in name_similarity
run `package-parser/tests/processing/migration/test_differ.py` in the main branch and in this branch and compare the running time
> feat: Improve calculating of Levenshtein Distance

- package-parser/package_parser/processing/api/__init__.py
- package-parser/package_parser/processing/api/_ast_visitor.py
- package-parser/package_parser/processing/api/_get_instance_attributes.py
- package-parser/tests/processing/api/test_instance_attributes.py
Closes #1184.
By inferencing over the attribute name, other types of the attribute can be found. They are added to the related attribute.
Convert an api via the `migrate` command and view the json file or run the test file `package-parser/tests/processing/api/test_instance_attributes.py`.
> feat: improve detection of attributes

- package-parser/package_parser/processing/api/_get_instance_attributes.py
- package-parser/package_parser/processing/api/model/_api.py
- package-parser/package_parser/processing/api/model/_types.py
Closes #1188.
If the type of an attribute is unknown, they will be added to the API as well.
run the api command with a class that has an attribute with no type hints.
> fix: generate attributes even their type is unknown

- .github/workflows/main.yml
- .github/workflows/pr.yml
- api-editor/gui/src/features/externalLinks/urlBuilder.ts
- codecov.yml
Closes #1263.
Upload test coverage reports to Codecov.
> ci: configure Codecov

- docs/package-parser/README.md
Closes #1284.
* Change `-s` to `-c`
> docs: fix `parse-package usages` flag

- api-editor/gui/src/features/externalLinks/urlBuilder.ts
Report missing/wrong annotation in the [Library-Analyzer](https://github.com/Safe-DS/Library-Analyzer) repo instead.
> fix: issue URLs

- api-editor/gui/src/features/annotations/DataCopyButtons.tsx
Closes #1297.
Use the browser API for the clipboard directly instead of the `useClipboard` hook.
> fix: copy to clipboard did not always work

- .eslintrc.js
- .github/workflows/main.yml
- .github/workflows/pr.yml
- api-editor/gui/build.gradle.kts
- api-editor/gui/jest.config.json
- api-editor/gui/package-lock.json
- api-editor/gui/package.json
- api-editor/gui/src/common/util/listOperations.test.ts
- api-editor/gui/src/common/util/stringOperations.test.ts
- api-editor/gui/src/common/util/validation.test.ts
- api-editor/gui/src/common/validation.test.ts
- api-editor/gui/src/features/annotations/mergeAnnotationStores.test.ts
- api-editor/gui/src/features/annotations/versioning/migrations.test.ts
- api-editor/gui/src/features/externalLinks/urlBuilder.test.ts
- api-editor/gui/src/features/filter/model/AbstractPythonFilter.test.ts
- api-editor/gui/src/features/filter/model/filterFactory.test.ts
- api-editor/gui/src/features/packageData/model/PythonClass.test.ts
- api-editor/gui/src/features/packageData/model/PythonFromImport.test.ts
- api-editor/gui/src/features/packageData/model/PythonFunction.test.ts
- api-editor/gui/src/features/packageData/model/PythonImport.test.ts
- api-editor/gui/src/features/packageData/model/PythonModule.test.ts
- api-editor/gui/src/features/packageData/model/PythonPackage.test.ts
- api-editor/gui/src/features/packageData/model/PythonParameter.test.ts
- api-editor/gui/src/features/packageData/model/PythonResult.test.ts
- api-editor/gui/src/features/packageData/treeView/HeatMapTag.test.ts
- api-editor/gui/src/features/statistics/StatisticView.test.ts
- codecov.yml
- package-lock.json
- package.json
Closes #1314.
Use `vitest` instead of `jest` as the testing framework.
> test: replace `jest` with `vitest`
